spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:55506/test_rocketmq?serverTimezone=GMT%2B8
    #  useUnicode=true&characterEncoding=utf-8&useSSL=false